### ISSUE TITLE
Audio Recording Example needed

### ISSUE THREAD

**Issue by tmccurdy** [Temasys/AdapterJS#113]
Sorry if this is the wrong place for posting this, and I may have missed something somewhere, but I cannot find any example of how to record audio using your plugin.  An example like this is needed!  

I understand how to get the plugin to work, prompt the user, get the media stream, maybe get an audio track?... OK, then what?  I really just need to get the data coming in on the audio buffer and store it in JS, then post it to the server, but this is not intuitive.

What is a best practice or example for doing this?

**Comment by johache** [comment]
Hi,
The plugin currently does not support recording.
There is actually no way of extracting the raw stream of data yet. 
We only support rending, which is also done by the plugin and in plugin <object>s.

We are thinking of good ways to offer an API for this. 
An implementation might come over the next 6 months, but I cannot give you a date yet.

May I know what your use case was ?

**Comment by tmccurdy** [comment]
OK, I was hoping that somehow it could be attached to an "audio" element or something and then intercept the stream from that?  Or even some kind of "proxy" audio element (but then you'd be taking over browser implementations of the audio element).  It seems that I will still need to use a Silverlight "shim" for IE then.

Our use-case is that we record audible answers from Test Subjects and upload them to a web server for review.

**Comment by agouaillard** [comment]
you want to take a look at the "media capture from DOM element
<http://www.w3.org/TR/2015/WD-mediacapture-fromelement-20150219/>" spec.
One early version is implemented in Firefox. I'm not familiar with the
audio part of it, though, but it is exactly what you want. Martin thompson
at mozilla would be your contact for questions.

Now, for a plugin to "pass on" data to the JS level is quite complicated,
so you cannot chain a plugin element with, say, a web audio element, or a
record-to-file element directly, like you would be able with a <video> or
<audio> element. You would need to smuggle the data to the JS side of
thing. It's quite difficult, and might not be useable (not fast enough)
even for audio. The problem is hard enough that chrome is not trying to do
that in iOS (to by pass webrtc restriction) and nobody else tried in the
community, even though there is a 10,000 USD bounty (see comment #13 here
<https://code.google.com/p/chromium/issues/detail?id=416226>). Don't hold
your breath.

HTH

On Mon, Sep 14, 2015 at 8:44 PM, tmccurdy <notifications@github.com> wrote:

> OK, I was hoping that somehow it could be attached to an "audio" element
> or something and then intercept the stream from that? Or even some kind of
> "proxy" audio element (but then you'd be taking over browser
> implementations of the audio element). It seems that I will still need to
> use a Silverlight "shim" for IE then.
>
> Our use-case is that we record audible answers from Test Subjects and
> upload them to a web server for review.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Temasys/AdapterJS/issues/113#issuecomment-140058879>.
>



-- 
Alex. Gouaillard, PhD, PhD, MBA
------------------------------------------------------------------------------------
President - CoSMo Software Consulting, Singapore
------------------------------------------------------------------------------------
sg.linkedin.com/agouaillard

   -

**Comment by tmccurdy** [comment]
Yes, and that's where I am at.  I can do what I need using plain-ole' JS in Firefox and Chrome.  It seems I will need to fall back to Silverlight on IE (well, unless the users have the new IE "Microsoft Edge" https://www.microsoft.com/en-us/windows/microsoft-edge, which will probably only be available on Win10).

**Comment by agouaillard** [comment]
**unofficially,**

the edge build with all ORTC implementation and a JS shim will be available
next week for non microsoft user with early access. The way it works at
microsoft is :
- internal build
=> beta build pushed to special whatever subscriber (did not get the name)
=> public builds

The build is already final and working internally.

Alex.

On Tue, Sep 15, 2015 at 12:46 PM, tmccurdy <notifications@github.com> wrote:

> Yes, and that's where I am at. I can do what I need using plain-ole' JS in
> Firefox and Chrome. It seems I will need to fall back to Silverlight on IE
> (well, unless the users have the new IE "Microsoft Edge"
> https://www.microsoft.com/en-us/windows/microsoft-edge, which will
> probably only be available on Win10).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Temasys/AdapterJS/issues/113#issuecomment-140279289>.
>



-- 
Alex. Gouaillard, PhD, PhD, MBA
------------------------------------------------------------------------------------
President - CoSMo Software Consulting, Singapore
------------------------------------------------------------------------------------
sg.linkedin.com/agouaillard

   -

**Comment by dmahadi-telepathy-ai** [comment]
Hi @johache ,

May I know the status of this request? is this feature possible now?

Regards,
Daniel Mahadi

**Comment by tmccurdy** [comment]
I ended up using a small Silverlight shim for IE11.  I made them JS and Silverlight using a common "api" that eventually called back into a small JS Worker.  It was a little complex because I had to tweak memory management as I allowed for continuous recording and recorded several audio clips on one page, posting back results asynchronously as they could (MSG Queuing).
