### ISSUE TITLE
AdapterJS.renderNotificationBar optinal?

### ISSUE THREAD

**Issue by papaloizouc** [Temasys/AdapterJS#128]
i was wandering if it would make sense to make the notification bar optional. It could be a case of switching from browser to mobile app or a case of the video being part of the functionality on the site. https://github.com/Temasys/AdapterJS/blob/1ddd382046f592c6c2d76d4da9701f6ff8c308ff/source/adapter.js#L301

**Comment by johache** [comment]
Hi
- When running on mobile browsers that don't have webrtc support, the popup shows to inform the user that webrtc is not available (because plugins don't exist on mobile). If you have a scenario where the popup offers to install the plugin this would be a bug.
- If you want to disable the popup on your website (custom), you can do so by setting AdapterJS.options.hidePluginInstallPrompt to true.
This would disable the install banner, as well as the one I described above.
