### ISSUE TITLE
stream print <JSAPI-Auto Javascript Object> in safari ?

### ISSUE THREAD

**Issue by rohitha123** [Temasys/AdapterJS#145]
Hi, I was trying to use the adapterjs with recordRTC and found that onMediaSuccess call back it return array saying "TypeError: Type error" and I print to see what stream is and then it was like below. any idea to solve this ?

var onMediaSuccess = function(stream) {
    console.log(stream);
}

console result was -> JSAPI-Auto Javascript Object

**Comment by johache** [comment]
All plugin objects are ActiveX objects on IE and NPAPI objects on other browsers.
This is a limitation due to the plugin interface, there isn't anything to do about it.

When logging an object in the console, Safari will stop at the NPAPI object level. However, you can still access its attributes. For example, ```console.log(stream.id); ``` will return a string.
IE is a little bit better at this and will show you more details.

I don't know how recordRTC works internally, but you will probably have issues with it not being written to communicate with ActiveX/NPAPI objects.
If you continue working on this, I'd be very happy to know how it goes :)

**Comment by sgrinich** [comment]
Hey @rohitha123 @johache , I'm running into the same Type error. Any resolution on your end that you would recommend?

**Comment by johache** [comment]
It's not an error. See my previous comment for details...
