### ISSUE TITLE
Questions about __TemWebRTCReady0

### ISSUE THREAD

**Issue by ibc** [Temasys/AdapterJS#29]
```
__TemWebRTCReady0 = function () {
  arguments.callee.StaticWasInit = arguments.callee.StaticWasInit || 1;
  if (arguments.callee.StaticWasInit === 1) {
    AdapterJS.WebRTCPlugin.documentReadyInterval = setInterval(function () {
      if (document.readyState === 'complete') {
        // TODO: update comments, we wait for the document to be ready
        clearInterval(AdapterJS.WebRTCPlugin.documentReadyInterval);
        AdapterJS.WebRTCPlugin.pluginState = AdapterJS.WebRTCPlugin.PLUGIN_STATES.READY;
      }
    }, 100);
  }
  arguments.callee.StaticWasInit++;
};
```

Questions:

* Why isn't this function declared with `var`?
* Must it be a global function (I mean, should it exist in the `window` global namespace)? Could it be a local function not exposed in `window`?
* It seems to set the plugin state to READY once the DOM becomes ready, but it just does it if `arguments.callee.StaticWasInit === 1`. Otherwise it increments `StaticWasInit` and does NOT set READY state. In which case could `StaticWasInit` has a value != 1?
* Is this method related to loading the plugin in two different tabs of the browser?
* ECMAScript 5 forbids the use of `arguments.callee` in strict mode: [link](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/arguments/callee). Could not the same effect be implemented by using a local counter variable or a counter within the `AdapterJS.WebRTCPlugin` object?

**Comment by johache** [comment]
- Why isn't this function declared with var?
Given that ```__TemWebRTCReady0```is defined in the global scope, I don't think this would make any difference


- Must it be a global function (I mean, should it exist in the window global namespace)? Could it be a local function not exposed in window?
If you are talking about namespacing it into AdapterJS, I would love to, I tried before, but the ```onload``` callback from the plugin (not defined by me) would not accept it;


- It seems to set the plugin state to READY once the DOM becomes ready, but it just does it if arguments.callee.StaticWasInit === 1. Otherwise it increments StaticWasInit and does NOT set READY state. In which case could StaticWasInit has a value != 1?
I use StaticWasInit as a static variable (as from C/C++) in order to start this interval only once.
I just realised that this is a bit of a legacy. ```__TemWebRTCReady0``` used to make a callback which should only be done once;
However, setting ```AdapterJS.WebRTCPlugin.pluginState``` N times would not be an issue, so I might be able to remove this safety.
Needs to be tested first though


- Is this method related to loading the plugin in two different tabs of the browser?
No, AFAIK, JS scope is limited to the local tab.

- ECMAScript 5 forbids the use of arguments.callee in strict mode: link. Could not the same effect be implemented by using a local counter variable or a counter within the AdapterJS.WebRTCPlugin object?
That is a good point. Again, legacy, we didn't used to have this nice namespacing when I first wrote this.
I suppose this is possible, but give my previous point, I might even be able to remove it completely;

I'll open a ticket and try to give it a quick try either today or tomorrow;

**Comment by ibc** [comment]
> Given that __TemWebRTCReady0is defined in the global scope, I don't think this would make any difference

That's why I also asked for allowing a private-scope function :)

>> Must it be a global function (I mean, should it exist in the window global namespace)? Could it be a local function not exposed in window?
> If you are talking about namespacing it into AdapterJS, I would love to, I tried before, but the onload callback from the plugin (not defined by me) would not accept it;

Here the "issue" seems to be the fact that `onload` receives the name of the callback as a string, instead of setting it with the callback function itself. Is there any reason for it to be a string? I mean:

* Actually:
```
// The object to store plugin information
AdapterJS.WebRTCPlugin.pluginInfo = {
  onload : '__TemWebRTCReady0'
};
```

* My suggestion:
* Actually:
```
// The object to store plugin information
AdapterJS.WebRTCPlugin.pluginInfo = {
  onload : __TemWebRTCReady0
};
```

In this way such a function could be a local one (non global) declared in a private scope (anything between `{` and `}`).

**Comment by johache** [comment]
The plugin actually takes the name of the function as a parameter, not the function itself.
See the plugin injection code:
``` '<param name="onload" value="' + AdapterJS.WebRTCPlugin.pluginInfo.onload + '" />' ```
So I am storing the function name on purpose.

What would still be nice however would be to take the function out of the global scope and to give the namespaced function name to ```onload````
Unfortunately, my previous tests show that ```onload``` is not capable of calling a namespaced function;

I will open a question, but it is not to be expected.

**Comment by ibc** [comment]
Clear. I've tried by setting `plugin.onload = function() { ... }` but it does not work at all (and it should not). In fact it is a "param" within the HTML element tag. So ok.

**Comment by johache** [comment]
FYI,
just pushed a correction on development removing this static aberration.

Closing

**Comment by ibc** [comment]
:cake:
