### ISSUE TITLE
How to reduce the loading time?

### ISSUE THREAD

**Issue by dongkai1993** [Temasys/AdapterJS#298]
The adapter.screenshare.js need to visit cdn.temasys.com at the begining of loading, sometimes, visit the website will be too slow in China.
How can I solve the problem?

**Comment by johache** [comment]
If you mean that it's hosted on cdn.temasys.io, you can make a copy of AJS on your own servers in China.
If you are talking about the download of the plugin, it would be a 1 time download, so possibly not such a big deal ? Otherwise, you can also make a copy of it on your servers and just modify ```AdapterJS.pluginInfo```

**Comment by dongkai1993** [comment]
I had download `adapter.screenshare.js`, but it would send a request to get `detectRTC.html`, we can get request url , "https://cdn.temasys.com.sg/skylink/extensions/detectRTC.html".
I guess that `adapter.screenshare.js` want to detect the browser whether to support screenshare. I tried to put the html on our server, and modify the url in `adapter.screenshare.js`, but it not work well.

**Comment by johache** [comment]
Hum, can you give it another try ? Hosting detectRTC.html on your own servers should work fine.
All this file does is check for the Chrome screenshare extension is installed, and if not, offer to download it.

**Comment by dongkai1993** [comment]
I try to put detectRTC.html on my servers, but getUserMedia throw "Extension is disabled" when I want to create a screenshare stream. Create camera stream work fine.
Dose screenshare browser plugin(Skylink WebRTC Tools) only allow the html's doamin is 'cdn.temasys.com.sg' ?

**Comment by letchoo** [comment]
Hi @dongkai1993, could you proceed to continue this on [support.temasys.io](support.temasys.io)?

Right now, the extension would work if the detectRTC.html file was hosted on cdn.temasys.com.sg due to the restrictions set in the [chrome extension itself that is downloaded from the store](https://chrome.google.com/webstore/detail/skylink-webrtc-tools/ljckddiekopnnjoeaiofddfhgnbdoafc).

That however if you would like to host the detectRTC.html yourself, or wish not to use the detectRTC.html file mechanism, we will provide you the steps to do so with the extension source code so you can reference your own domain into it to work.

**Comment by dongkai1993** [comment]
@letchoo Thank you!
Please tell me the steps.

**Comment by iyharini** [comment]
Hi @dongkai1993 Could you create a Support Ticket for this on our portal here: http://support.temasys.com.sg/support/tickets/new so we can assist further? Alternatively, if you could share your email id, I'd be glad to create one for you.
