### ISSUE TITLE
What is hasCredentials?

### ISSUE THREAD

**Issue by ibc** [Temasys/AdapterJS#32]
```
iceServers[i].hasCredentials = AdapterJS.
            isDefined(iceServers[i].username) &&
            AdapterJS.isDefined(iceServers[i].credential);
```

Why is that `hasCredentials` for? is that needed for the plugin to properly connect to TURN servers?

**Comment by johache** [comment]
Yes it is.
I cannot check for the existence of the username-credential pair from the plugin as it might crash if one of them is undefined (bad access from the C++ code).
My solution was to set a bool no matter what, so that I know whether or not I can access the pair;

Please close if that answers your question.

**Comment by ibc** [comment]
Thanks.
