### ISSUE TITLE
getUserMedia issue

### ISSUE THREAD

**Issue by jauhenk** [Temasys/AdapterJS#89]
Hey,
I've found an issue with getUserMedia.
When I use audio and video streams and call getUserMedia second time I get an error "Failed to create video track".
Could you please take a look?

**Comment by serrynaimo** [comment]
Do you have some more information about browser/os use-case? with or without plugin?

**Comment by z0r1k** [comment]
Could it be related to this issue? https://github.com/Temasys/AdapterJS/issues/79

**Comment by johache** [comment]
If you are on Windows, this is probably a know limitation, coming from the OS.
Windows will only let 1 capturer exist on any camera at any one time.
On Mac, this limitation does not exist.

If that was the issue, this is a won't fix. Closing the issue.

**Comment by mhofman** [comment]
@johache I believe the plugin should be able to successfully handle multiple active streams following multiple gUM calls in the same tab, even on Windows. Is that the case right now?
Of course you can't make the same assurance in multiple tabs since the plugin might get loaded in separate processes.

**Comment by vinayakkedge** [comment]
I am facing this issue right now.  Can somebody help me with this?

**Comment by johache** [comment]
See my answer above.
